from enum import Enum

# Body parts only we are interested mention here
class Body(Enum):
    NOSE = 0
    LEFT_EYE_INNER = 1
    LEFT_EYE = 2
    LEFT_EYE_OUTER = 3
    RIGHT_EYE_INNER = 4
    RIGHT_EYE = 5
    RIGHT_EYE_OUTER = 6
    LEFT_EAR=7
    RIGHT_EAR=8
    MOUTH_LEFT = 9
    MOUTH_RIGHT = 10
    LEFT_SHOULDER = 11
    RIGHT_SHOULDER = 12
    LEFT_ELBOW = 13
    RIGHT_ELBOW = 14
    LEFT_WRIST = 15
    RIGHT_WRIST = 16
    LEFT_PINKY = 17
    RIGHT_PINKY = 18
    LEFT_INDEX = 19
    RIGHT_INDEX = 20
    LEFT_THUMB = 21
    RIGHT_THUMB = 22
    LEFT_HIP = 23
    RIGHT_HIP = 24
    LEFT_KNEE = 25
    RIGHT_KNEE = 26
    LEFT_ANKLE = 27
    RIGHT_ANKLE =28
    LEFT_HEEL = 29
    RIGHT_HEEL = 30
    LEFT_FOOT_INDEX = 31
    RIGHT_FOOT_INDEX = 32

class Upper_Body(Enum):
    LEFT_SHOULDER = 11
    RIGHT_SHOULDER = 12
    LEFT_ELBOW = 13
    RIGHT_ELBOW = 14
    LEFT_WRIST = 15
    RIGHT_WRIST = 16


class Hand(Enum):
    WRIST = 0
    THUMB_CMC = 1
    THUMB_MCP = 2
    THUMB_IP = 3
    THUMB_TIP = 4
    INDEX_FINGER_MCP = 5
    INDEX_FINGER_PIP = 6
    INDEX_FINGER_DIP = 7
    INDEX_FINGER_TIP = 8
    MIDDLE_FINGER_MCP = 9
    MIDDLE_FINGER_PIP = 10
    MIDDLE_FINGER_DIP = 11
    MIDDLE_FINGER_TIP = 12
    RING_FINGER_MCP = 13
    RING_FINGER_PIP = 14
    RING_FINGER_DIP = 15
    RING_FINGER_TIP = 16
    PINKY_MCP = 17
    PINKY_PIP = 18
    PINKY_DIP = 19
    PINKY_TIP = 20

# 15 angles for each hand
class HAND_ANGLES(Enum):
    WRIST_THUMB_CMC_MCP = (Hand.WRIST, Hand.THUMB_CMC, Hand.THUMB_MCP)
    THUMB_CMC_MCP_IP = (Hand.THUMB_CMC, Hand.THUMB_MCP, Hand.THUMB_IP)
    THUMB_MCP_IP_TIP = (Hand.THUMB_MCP, Hand.THUMB_IP, Hand.THUMB_TIP)
    WRIST_INDEX_FINGER_MCP_PIP = (Hand.WRIST, Hand.INDEX_FINGER_MCP, Hand.INDEX_FINGER_PIP)
    INDEX_FINGER_MCP_PIP_DIP = (Hand.INDEX_FINGER_MCP, Hand.INDEX_FINGER_PIP, Hand.INDEX_FINGER_DIP)
    INDEX_FINGER_PIP_DIP_TIP = (Hand.INDEX_FINGER_PIP, Hand.INDEX_FINGER_DIP, Hand.INDEX_FINGER_TIP)
    WRIST_MIDDLE_FINGER_MCP_PIP = (Hand.WRIST, Hand.MIDDLE_FINGER_MCP, Hand.MIDDLE_FINGER_PIP)
    MIDDLE_FINGER_MCP_PIP_DIP = (Hand.MIDDLE_FINGER_MCP, Hand.MIDDLE_FINGER_PIP, Hand.MIDDLE_FINGER_DIP)
    MIDDLE_FINGER_PIP_DIP_TIP = (Hand.MIDDLE_FINGER_PIP, Hand.MIDDLE_FINGER_DIP, Hand.MIDDLE_FINGER_TIP)
    WRIST_RING_FINGER_MCP_PIP = (Hand.WRIST, Hand.RING_FINGER_MCP, Hand.RING_FINGER_PIP)
    RING_FINGER_MCP_PIP_DIP = (Hand.RING_FINGER_MCP, Hand.RING_FINGER_PIP, Hand.RING_FINGER_DIP)
    RING_FINGER_PIP_DIP_TIP = (Hand.RING_FINGER_PIP, Hand.RING_FINGER_DIP, Hand.RING_FINGER_TIP)
    WRIST_PINKY_MCP_PIP = (Hand.WRIST, Hand.PINKY_MCP, Hand.PINKY_PIP)
    PINKY_MCP_PIP_DIP = (Hand.PINKY_MCP, Hand.PINKY_PIP, Hand.PINKY_DIP)
    PINKY_PIP_DIP_TIP = (Hand.PINKY_PIP, Hand.PINKY_DIP, Hand.PINKY_TIP)

# 9 distance measures for each hand
class HAND_DISTANCE_PAIRS(Enum):
    THUMB_CMC_TIP = (Hand.THUMB_CMC, Hand.THUMB_TIP)
    INDEX_MCP_TIP = (Hand.INDEX_FINGER_MCP, Hand.INDEX_FINGER_TIP)
    MIDDLE_MCP_TIP = (Hand.MIDDLE_FINGER_MCP, Hand.MIDDLE_FINGER_TIP)
    RING_MCP_TIP = (Hand.RING_FINGER_MCP, Hand.RING_FINGER_TIP)
    PINKY_MCP_TIP = (Hand.PINKY_MCP, Hand.PINKY_TIP)
    THUMB_TIP_INDEX_TIP = (Hand.THUMB_TIP,Hand.INDEX_FINGER_TIP)
    INDEX_TIP_MIDDLE_TIP = (Hand.INDEX_FINGER_TIP,Hand.MIDDLE_FINGER_TIP)
    MIDDLE_TIP_RING_TIP = (Hand.MIDDLE_FINGER_TIP,Hand.RING_FINGER_TIP)
    RING_TIP_PINKY_TIP = (Hand.RING_FINGER_TIP,Hand.PINKY_TIP)

# 6 body measures
class BODY_ANGLES(Enum):
    R_SHOULDER_L_SHOULDER_L_ELBOW = (Body.RIGHT_SHOULDER, Body.LEFT_SHOULDER,Body.LEFT_ELBOW)
    L_SHOULDER_L_ELBOW_L_WRIST = (Body.LEFT_SHOULDER,Body.LEFT_ELBOW,Body.LEFT_WRIST)
    L_ELBOW_L_WRIST_L_PINKY = (Body.LEFT_ELBOW, Body.LEFT_WRIST, Body.LEFT_PINKY)
    L_SHOULDER_R_SHOULDER_R_ELBOW = (Body.LEFT_SHOULDER, Body.RIGHT_SHOULDER, Body.RIGHT_ELBOW)
    R_SHOULDER_R_ELBOW_R_WRIST = (Body.RIGHT_SHOULDER, Body.RIGHT_ELBOW, Body.RIGHT_WRIST)
    R_ELBOW_R_WRIST_R_PINKY = (Body.RIGHT_ELBOW, Body.RIGHT_WRIST, Body.RIGHT_PINKY)

# 2 body distance measures
class BODY_DISTANCE_PAIRS(Enum):
    L_SHOULDER_L_WRIST = (Body.LEFT_SHOULDER,Body.LEFT_WRIST)
    R_SHOULDER_R_WRIST = (Body.RIGHT_SHOULDER,Body.RIGHT_WRIST)


# 56 feature vector for each frame

class HAND_JOINTS(Enum):
    L_WRIST = 0
    L_THUMB_CMC = 1
    L_THUMB_MCP = 2
    L_THUMB_IP = 3
    L_THUMB_TIP = 4
    L_INDEX_FINGER_MCP = 5
    L_INDEX_FINGER_PIP = 6
    L_INDEX_FINGER_DIP = 7
    L_INDEX_FINGER_TIP = 8
    L_MIDDLE_FINGER_MCP = 9
    L_MIDDLE_FINGER_PIP = 10
    L_MIDDLE_FINGER_DIP = 11
    L_MIDDLE_FINGER_TIP = 12
    L_RING_FINGER_MCP = 13
    L_RING_FINGER_PIP = 14
    L_RING_FINGER_DIP = 15
    L_RING_FINGER_TIP = 16
    L_PINKY_MCP = 17
    L_PINKY_PIP = 18
    L_PINKY_DIP = 19
    L_PINKY_TIP = 20
    R_WRIST = 21
    R_THUMB_CMC = 22
    R_THUMB_MCP = 23
    R_THUMB_IP = 24
    R_THUMB_TIP = 25
    R_INDEX_FINGER_MCP = 26
    R_INDEX_FINGER_PIP = 27
    R_INDEX_FINGER_DIP = 28
    R_INDEX_FINGER_TIP = 29
    R_MIDDLE_FINGER_MCP = 30
    R_MIDDLE_FINGER_PIP = 31
    R_MIDDLE_FINGER_DIP = 32
    R_MIDDLE_FINGER_TIP = 33
    R_RING_FINGER_MCP = 34
    R_RING_FINGER_PIP = 35
    R_RING_FINGER_DIP = 36
    R_RING_FINGER_TIP = 37
    R_PINKY_MCP = 38
    R_PINKY_PIP = 39
    R_PINKY_DIP = 40
    R_PINKY_TIP = 41
